# Publishes package snapshots (-dev-xyz) to npmjs.com
#
# - Assumes that pnpm is set up correctly and that dependencies are installed.
#   in the calling repository for fixing package.json dependencies.
#   This is a temporary solution that should be replaced with a more stable alternative.
name: Publish Snapshots
description: Publish development snapshots to the npm registry
inputs:
  npm-token:
    description: NPM token for publishing packages
    required: true
  snapshot-tag:
    description: Name of the snapshot build tag (e.g. "dev")
    required: false
    default: "dev"
  build-command:
    description: Command to build packages (e.g. "build-packages")
    required: false
    default: "build-packages"
runs:
  using: "composite"
  steps:
    # Bumps versions in package.json (see https://github.com/changesets/changesets/blob/main/docs/snapshot-releases.md)
    # The changes should not be committed to any branch: the "releases" are not part of the version history.
    - name: Version packages
      shell: bash
      run: |
        echo "Publishing snapshot from ${{ github.ref_name}} using tag ${{ inputs.snapshot-tag }}"
        pnpm changeset version --snapshot ${{ inputs.snapshot-tag }}

    # Note: must happen after versioning because the updated package.json files will be copied into dist/
    - name: Build packages
      shell: bash
      run: pnpm ${{ inputs.build-command }}

    - name: Publish packages
      shell: bash
      run: |
        pnpm publish -r --access public --tag ${{ inputs.snapshot-tag }} --no-git-checks --report-summary
      env:
        NODE_AUTH_TOKEN: ${{ inputs.npm-token }}

    - name: List packages
      shell: bash
      run: |
        echo "Published packages"
        echo "=================="
        echo ""
        jq -r '.publishedPackages[] | "- \(.name)@\(.version)"' pnpm-publish-summary.json
