# Moves new issues or prs to the maintenance board.
# Requires a github token with authorization to assign issues to boards in this organization.
name: Add to maintenance board
description: Assign new issues to the maintenance board.
inputs:
  github-token:
    description: "GitHub PAT for editing the issue / project"
    required: true

runs:
  using: "composite"
  steps:
    - name: "Add to project"
      uses: actions/add-to-project@5afcf98fcd03f1c2f92c3c83f58ae24323cc57fd # v2.0.0
      with:
        project-url: https://github.com/orgs/open-pioneer/projects/6
        github-token: ${{ inputs.github-token }}
        # Don't include renovate stuff
        labeled: dependencies
        label-operator: NOT
